namespace: prod
resources:
- ../../base

images:
  - name: nginx
    newName: nginx
    newTag: latest

# patchesStrategicMerge
patches:
  dev-patch.yaml

namespace: prod
namePrefix: prod-
# configMapGenerator
configMapGenerator:
- name: env-vars        # base에 지정된 configMap의 이름
  envs:
    - prod.env        
